### ISSUE TITLE
Discount

### ISSUE THREAD

**Issue by Wicht1** [pardus79/woocommerce-bitcoin-price-display#2]
Hello and first: **Thank you for your great work.**

Many shops offer a discount when you pay with Bitcoin. We also do this in our shop  ([Dezentralshop](https://dezentralshop.ch))

II have a feeling that your method of implementing the Satoshi price is much faster than my approach. Nevertheless, it would be great to retain the old functionality of the discounted price.

My plugin works basically like this:

_(Whole File in Attachment)_

### Get the Exchange Rate

>// Funktion zum Abrufen des Wechselkurses
function get_exchange_rate($currency) {
    $url = "https://bitpay.com/api/rates/btc/" . $currency;
    $response = json_decode(file_get_contents($url), true);
    if (!isset($response["rate"])) {
        return 0;
    }
    return $response["rate"];
}

### Get the Discount

> // Funktion zum Abrufen des Rabattwerts
> function get_discount() {
>     global $wpdb;
>     $product_id = get_the_ID();
>     $meta_value = $wpdb->get_var($wpdb->prepare("SELECT meta_value FROM $wpdb->postmeta WHERE meta_key = '_alg_checkout_fees_value_btcpay' AND post_id = %d", $product_id));
>     return absint($meta_value);
> }

This function retrieves the individually set discount from the plugin. `Payment Gateway Based Fees and Discounts for WooCommerce Pro` [Link](https://www.tychesoftwares.com/products/woocommerce-payment-gateway-based-fees-and-discounts-plugin/)

### than build Shortcodes

> // Shortcode für die Anzeige des Satoshi-Preises mit Rabatt
> function satoshi_price_with_discount_shortcode() {
>     global $product;
>     if (!$product) {
>         return;
>     }
>     $price = $product->get_price();
>     $discount = get_discount(); // Rabattwert abrufen
>     $discounted_price = $price - ($price * $discount / 100); // Berechne den rabattierten Preis
>     $exchange_rate = get_exchange_rate("CHF");
>     $price_in_bitcoin = $discounted_price / $exchange_rate;
>     $price_in_satoshi = round($price_in_bitcoin * 100000000);
>     $price_in_satoshi = number_format($price_in_satoshi, 0, '.', "'");
>     return '<span class="satDiscount">SAT ' . $price_in_satoshi . '</span>';
> }
> add_shortcode('satoshi_price_with_discount', 'satoshi_price_with_discount_shortcode');

## Question

Is it possible to implement such a function in this plugin? Or should I fork it and build one using your technique and this functionality?
I am not a developer and have absolutely no clue what I'm doing. I just search for code snippets and ask ChatGPT to combine them.
You might need the whole PHP file to understand the context (if you even look at it), so I will provide it here.

[BTC-Preis_Funktioniert.txt](https://github.com/user-attachments/files/16036781/BTC-Preis_Funktioniert.txt)

**Comment by pardus79** [comment]
Discounts added to the latest release 👍
